- surrealdb/client.py
Simple oversight on HTTP Client where if an error was returned, the status was checked too late and resulted in serialization errors.
> Fix HTTP Client response errors being checked at the incorrect time

- surrealdb/clients/ws.py
This PR provides more efficient & reliable logic for matching requests and responses.
> Replace request-waiting logic to use asyncio.Future

- surrealdb/clients/http.py
- surrealdb/clients/ws.py
Add documentation to certain methods within the ws and http clients.
Some methods are left blank if I was unsure of what they do.
> Add documentation to methods

- examples/http_client_example.py
> Fixes typo in http_client_example.py

- surrealdb/clients/http.py
> Fix unhandled `KeyError`

- README.md
I copied over some images and badges from the README for SurrealDB in to the README for the python driver and reformatted the badges. Feel free to tell me if I should remove some of the badges for the pull request to get merged.
> Add image and some new badges to README

- poetry.lock
Resolve a moderate severity [Dependabot alert](https://github.com/surrealdb/surrealdb.py/security/dependabot/1) on certifi.
Update the dependencies using `poetry update` which creates a new `poetry.lock` file
Manual testing or for now running the examples in the project.
Yes, this Dependabot alert https://github.com/surrealdb/surrealdb.py/pull/47
> Updating dependencies to resolve a moderate severity Dependabot alert

- surrealdb/http.py
Interested in learning Rust, so I decided to choose this project for my contribution. I already know Python and want to become familiar with the codebase. 
This commit refactors the API calling methods in the codebase to improve their readability, maintainability, and performance. The changes include simplifying nested if statements, reducing code duplication, and improving naming conventions. These changes should make it easier to understand and modify the code in the future, as well as reducing the likelihood of bugs and errors.
Test Plan:
- Verify that the API calling methods have been refactored and optimized for improved readability and maintainability.
- Test the all the API calling methods 
No
[Contributing Guidelines]: https://github.com/surrealdb/surrealdb/blob/main/CONTRIBUTING.m …
> Refactor : API calling methods

- .github/workflows/ruff.yml
- pyproject.toml
- surrealdb/__init__.py
Harder to maintain code quality
Implements a workflow that runs on push and pr that runs ruff in order to maintain code quality
> ci: Create a workflow that runs ruff

- pyproject.toml
> Bump to 0.3.1

- surrealdb/ws.py
Documentation improvements
Corrects the example URL.
> docs: fix typo in ws.py

- .github/workflows/cross_build.yml
> trying out new build

- pyproject.toml
- surrealdb/ws.py
Two words: dependency hell.  
I'm using Pydantic V2's features as part of a project, and updating wasn't particularly difficult--just change `allow_mutation = False` to `frozen = True`, bump the version number, and Bob's your uncle.
I ran the updated version, as part of my project, locally. No major issues cropped up.
> Upgrade to Pydantic V2

- pyproject.toml
> Bump to 0.3.2

- surrealdb/connection.py
- surrealdb/connection_clib.py
- surrealdb/connection_factory.py
- surrealdb/connection_http.py
- surrealdb/connection_ws.py
- tests/unit/test_clib_connection.py
- tests/unit/test_http_connection.py
- tests/unit/test_ws_connection.py
Bug fix on Websocket connection notification queues 
> Issue fix for Notification queue

- dev_requirements.txt
- requirements.txt
Fix dependencies from dependabot recommendations
> dependency update

- README.md
Found a small issue in the documentation that can cause confusion when writing custom queries, the old version before rewrite was correct
Added a missing character to the Readme
Verified locally that adding $ sign to the query fixes the issue in the documentation
> Small documentation fix

- .github/workflows/stability.yml
- .github/workflows/tests.yml
- src/surrealdb/cbor2/_encoder.py
- src/surrealdb/data/cbor.py
- tests/unit_tests/connections/invalidate/test_async_http.py
- tests/unit_tests/connections/invalidate/test_async_ws.py
- tests/unit_tests/connections/invalidate/test_blocking_http.py
- tests/unit_tests/connections/invalidate/test_blocking_ws.py
- tests/unit_tests/data_types/test_datetimes.py
- tests/unit_tests/data_types/test_none.py
To fix CI in main repo
Fixes Timzone changeing when decoding cbor
Fix CI Fail because Table `person` has 2 diffrent schemas.
Adds manuel Actions dispatch for testing in our none main branches
This fixes tests, so...
> Fix CI / CD for main repo & Timezone offset when decoding cbor

- src/surrealdb/data/cbor.py
- tests/unit_tests/data_types/test_decimal.py
to provide decimal support
Added a test script in `tests/unit_tests/data_types/test_decimal.py`.
> adding decimal support

- src/surrealdb/connections/utils_mixin.py
- src/surrealdb/data/cbor.py
- tests/unit_tests/data_types/test_geometry.py
To fix the following [issue](https://github.com/surrealdb/surrealdb.py/issues/168).
fix cbor tagging
A new test file has been added in `tests/unit_tests/data_types/test_geometry.py`.
this [issue](https://github.com/surrealdb/surrealdb.py/issues/168).
> fixing polygon issue
